config/routes.rb
Backpacker::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :questions do
    resources :paths, :only => [:create]
    resources :answers
  end
  
  get '/channel.html' => proc {
    [
      200,
      {
        'Pragma'        => 'public',
        'Cache-Control' => "max-age=#{1.year.to_i}",
        'Expires'       => 1.year.from_now.to_s(:rfc822),
        'Content-Type'  => 'text/html'
      },
      ['<script type="text/javascript" src="//connect.facebook.net/en_US/all.js"></script>']
    ]
  }

   root 'questions#index'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/path.rb
class Path < ActiveRecord::Base
  belongs_to :question
  belongs_to :from_user, :class_name => 'User', :primary_key => 'uid'
  belongs_to :to_user, :class_name => 'User', :primary_key => 'uid'
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers
	belongs_to :user
	has_many :paths
    
end

app/models/user.rb
### app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :omniauthable
  has_many :questions
  has_many :answers
  has_many :send_paths, :class_name => 'Path', :foreign_key => 'from_user_id'
  has_many :received_paths, :class_name => 'Path', :foreign_key => 'to_user_id'
  has_many :received_questions, :source => :to_user, :through => :received_paths

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :name, :provider, :uid
  # attr_accessible :title, :body

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20],
                         token:auth.credentials.token
                         )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  
  def facebook_friends
      access_token = self.token
      @graph = Koala::Facebook::API.new(access_token)
      friends = @graph.get_connections("me", "friends")
      return friends
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.build(params.require(:answer).permit(:answer))
		@answer.user_id = current_user.id

		if @answer.save
			redirect_to question_path(@question)
		else
			render action: 'new'
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController

	def create
		@path = Path.new(params.require(:path).permit(:to_user_id))
		@path.question_id = params[:question_id]
		@path.from_user_id = current_user.id
		if not @path.save
			render 'error'
		end

		if not User.find_by(uid: params[:path][:to_user_id])  
			redirect_to question_path(params[:question_id]), :flash => {:flag => "1", :dialog_request_id => params[:path][:to_user_id]}
		end
			redirect_to question_path(params[:question_id])
	end

	

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.all
		@received_questions = current_user.try(:received_questions)||[]
		@question = Question.new
	end

	def show
		@question = Question.find(params[:id])
		@answer = Question.find(params[:id]).answers.build
		@friends = current_user.try(:facebook_friends)
		@path = Path.new 
		@p = @question.paths.order("created_at ASC")
	#質問した人
	#pathからquestionidで引いて、created_atで順に引き出す.
	#0pathか1pathか2path以上かで分岐.
	#0pathは表示しなし
	#1pathはfromとto
	#2path以上はfromとtoでその後のto

	end

	def create
		@question = Question.new(params.require(:question).permit(:title, :content, :resolved))
		@question.user_id = current_user.id
		if @question.save
			redirect_to questions_path
		else
			render action: 'new'
		end
	end

	def new
		@question = Question.new
	end


	def destroy

	end


end

app/controllers/users/omniauth_callbacks_controller.rb
### app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/index.html.erb
test

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backpacker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'home', questions_path %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in? %>
  Sign in as <strong><%= current_user.name %></strong> 
  <h1><%= @question.user_id %></h1>
  <img width="2%" height="2%" src='<%= "https://graph.facebook.com/#{current_user.uid.to_s}/picture"%>' class="img-circle" />	
  | <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>
	
<%= yield %>


</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
<div class="field">
	<%= f.label :title %>
	<%= f.text_field :title %>	
</div>

<div class="field">
	<%= f.label :content %>
	<%= f.text_field :content %>
</div>

<div class="actions">

	<%= f.submit %>	
</div>

<% end %>

app/views/questions/index.html.erb
<h1>Backpacker</h1>

<h2>あなたに託されたクエスト</h2>


<div class="row-fluid"> 
<% @received_questions.each do |received_question| %>
	<div class="quest span4">
			<div class="row_fluid">
				<div class="span4">
					<%= link_to received_question.user.try(:name), question_path(received_question) %>
				</div>
				<div class="span8">
					<%= link_to received_question.title, question_path(received_question) %>
					<div class="row_fluid">
						<div class="span12">
						<%= link_to received_question.content, question_path(received_question) %>
						</div>
					</div>
				</div>
			</div>
	</div>
<% end %>
</div>







<h2>新着のクエスト</h2>
<% @questions.each_slice(3) do |questions| %>
<div class="row-fluid">
<% questions.each do |question| %>
	<div class="quest span4">
			<div class="row_fluid">
				<div class="span4">
					<%= link_to question.user.try(:name), question_path(question) %>
				</div>
				<div class="span8">
					<%= link_to question.title, question_path(question) %>
					<div class="row_fluid">
						<div class="span12">
						<%= link_to question.content, question_path(question) %>
						</div>
					</div>
				</div>
			</div>
	</div>
<% end %>
</div>
<% end %>

<h2>New Quest</h2>

<%= render 'form' %>

<%#= link_to 'New', new_question_path %>

app/views/questions/new.html.erb
<h1>new question</h1>

<%= render 'form' %>

<%= link_to 'home', questions_path %>

app/views/questions/show.html.erb
<h2>Quest</h2>
<div class="quest_t"><%= @question.title %></div>
<div class="quest_c"><%= @question.content %></div>
</ul>
<%= link_to 'home', questions_path %>

<h2>Path</h2>
<div>
<%=
	#質問した人
	#pathからquestionidで引いて、created_atで順に引き出す.
	#0pathか1pathか2path以上かで分岐.
	#0pathは表示しなし
	#1pathはfromとto
	#2path以上はfromとtoでその後のto
%>
	<ul>
	<li>
		<%= @question.user.name %><img width="2%" height="2%" src='<%= "https://graph.facebook.com/#{@question.user.uid.to_s}/picture"%>' class="img-circle" />
	</li>
	
	<% @p.each do |p| %>
		<li>
			<img width="2%" height="2%" src='<%= "https://graph.facebook.com/#{p.to_user_id.to_s}/picture"%>' class="img-circle" />
		</li>
	<% end %>
	

	</ul>

</div>

<h2>Comments</h2>
<ul>
<% if @question.answers.any? %>
<% @question.answers.each do |answer| %>
<div class="answer_u"> Username: <%= answer.user_id %> </div>
<div class="answer_c"> Answer: <%= answer.answer %></div>
<% end %>
<% else %>
<li>no comment yet</li>
<% end %>
</ul>

<h2>Add a Answer</h2>
<%= form_for([@question, @answer]) do |f| %>
<div class="field">
	<%= f.label :answer %>
	<%= f.text_field :answer %>
</div>
<div class="actions">
	<%= f.submit %>	
</div>
<% end %>

<h2>Path</h2>
<span>解決できそうな友人を紹介してみよう</span>
<%= form_for [@question, @path] do |f| %>
	<% @friends.each do |friend| %>
	<div class="field">
		<%= f.radio_button :to_user_id, friend["id"].to_i %><%= friend["name"] %>
	</div>
	<% end %>
	<div class="actions">
		<%= f.submit %>	
	</div>
<% end %>

<% if flash[:flag] %>
  <div id="fb-root"></div>
  <script src="http://connect.facebook.net/en_US/all.js">
  </script>
  <script>
    FB.init({ 
      appId:'205338842958928', cookie:true, 
      status:true, xfbml:true 
    });
	FB.ui({
	 method: 'apprequests',
	 message: 'facebookアプリのテストですよん.',
	  to: <%= flash[:dialog_request_id] %>,
	  data: 'send-to-one-42'
	});

  </script>
<% end %>


<%= link_to 'home', questions_path %>